version: '3'

services:
  reverse_proxy:
    container_name: reverse_proxy
    image: nginx
    volumes:
    - ./reverse_proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
    - "80:80"
    depends_on:
      - keycloak

  web:
    container_name: web
    image: nginx
    volumes:
      - ./web:/usr/share/nginx/html:ro

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.0.2
    ports:
    - "8080:8080"
    volumes:
      - ./keycloak_export/realm:/opt/keycloak/data/import:ro
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak_postgres:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak

      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin

      - KC_HOSTNAME_URL=http://localhost/keycloak
      - KC_HOSTNAME_ADMIN_URL=http://localhost/keycloak
      - PROXY_ADDRESS_FORWARDING=true
      - KC_PROXY=edge
    command: start --hostname-strict=false --import-realm
    depends_on:
      - keycloak_postgres

  pseudo_backend:
    container_name: pseudo_backend
    image: node:19-slim
    tty: true
    command: /bin/bash
    user: "1000:1000"
    volumes:
      - ./verify_jwt:/app:ro

  keycloak_postgres:
    container_name: keycloak_postgres
    image: postgres:13-alpine3.14
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
      - POSTGRES_DB=keycloak

  keycloak_export:
    container_name: keycloak_export
    build: ./keycloak_export
    ports:
    - "8081:8080"
    volumes:
      - ./keycloak_export/realm:/keycloak_export
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak_postgres:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak

      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    entrypoint: /bin/bash
    tty: true
    depends_on:
      - keycloak_postgres
    user: "1000:1000"
